var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
             "fulldaykey": "MMddyyyy",
            "fulldayshow": "d L yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W d/M",
            "Md3": "d L",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dim",
            "mon": "lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fév",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aoû",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Déc"
        },
        "no_implemented": "Pas encore implémenté",
        "to_date_view": "Cliquez à la vue de date actuelle",
        "i_undefined": "Undefined",
        "allday_event": "Toute les évènement de la journée",
        "repeat_event": "Répétez l'évènement",
        "time": "Date",
        "event": "Evènement",
        "location": "Emplacement",
        "participant": "Participant",
        "get_data_exception": "Erreur lors de la récupération des données",
        "new_event": "Nouvel évènement",
        "confirm_delete_event": "Voulez vous vraiment supprimer cet évènement ? ",
        "confrim_delete_event_or_all": "Voulez vous répéter tous les événements ou seulement cet événement ? \r\nCliquez [OK] pour supprimer seulement cet évènement, cliquez [Cancel] pour supprimer tous les évènements",
        "data_format_error": "Format de données erronée! ",
        "invalid_title": "Le titre d'événement ne peut pas être vide ou contient ($<>)",
        "view_no_ready": "La vue n'est pas prête",
        "example": "exemple., rencontre à 17:00",
        "content": "Sujet",
        "create_event": "Ajouter un évènement",
        "update_detail": "Modifier l'évènement",
        "click_to_detail": "Voir les détails",
        "i_delete": "Supprimer",
        "day_plural": "jours",
        "others": "Autres",
        "item": ""
    }
});
